# Single-container BlockPanel deployment (similar to Crafty style)
# Uses internal SQLite DB and no external dependencies.
# Run: docker compose -f docker-compose.single.yml up -d

services:
  blockpanel:
    image: ${BLOCKPANEL_IMAGE:-moresonsun/blockypanel}:${BLOCKPANEL_TAG:-latest}
    container_name: blockpanel
    # Comment build section if pulling pre-built image only.
    build:
      context: .
      dockerfile: docker/controller.Dockerfile
    ports:
      - "8000:8000"
      # Optional pre-reserved range if you want direct static port mapping for servers (controller dynamically creates containers)
      - "25500:25500"
      - "25501:25501"
      - "25502:25502"
      - "25503:25503"
      - "25504:25504"
      - "25505:25505"
      - "25506:25506"
      - "25507:25507"
      - "25508:25508"
      - "25509:25509"
      - "25510:25510"
      - "25511:25511"
      - "25512:25512"
      - "25513:25513"
      - "25514:25514"
      - "25515:25515"
      - "25516:25516"
      - "25517:25517"
      - "25518:25518"
      - "25519:25519"
      - "25520:25520"
      - "25521:25521"
      - "25522:25522"
      - "25523:25523"
      - "25524:25524"
      - "25525:25525"
      - "25526:25526"
      - "25527:25527"
      - "25528:25528"
      - "25529:25529"
      - "25530:25530"
      - "25531:25531"
      - "25532:25532"
      - "25533:25533"
      - "25534:25534"
      - "25535:25535"
      - "25536:25536"
      - "25537:25537"
      - "25538:25538"
      - "25539:25539"
      - "25540:25540"
      - "25541:25541"
      - "25542:25542"
      - "25543:25543"
      - "25544:25544"
      - "25545:25545"
      - "25546:25546"
      - "25547:25547"
      - "25548:25548"
      - "25549:25549"
      - "25550:25550"
      - "25551:25551"
      - "25552:25552"
      - "25553:25553"
      - "25554:25554"
      - "25555:25555"
      - "25556:25556"
      - "25557:25557"
      - "25558:25558"
      - "25559:25559"
      - "25560:25560"
      - "25561:25561"
      - "25562:25562"
      - "25563:25563"
      - "25564:25564"
      - "25565:25565"
      - "25566:25566"
      - "25567:25567"
      - "25568:25568"
      - "25569:25569"
      - "25570:25570"
      - "25571:25571"
      - "25572:25572"
      - "25573:25573"
      - "25574:25574"
      - "25575:25575"
      - "25576:25576"
      - "25577:25577"
      - "25578:25578"
      - "25579:25579"
      - "25580:25580"
      - "25581:25581"
      - "25582:25582"
      - "25583:25583"
      - "25584:25584"
      - "25585:25585"
      - "25586:25586"
      - "25587:25587"
      - "25588:25588"
      - "25589:25589"
      - "25590:25590"
      - "25591:25591"
      - "25592:25592"
      - "25593:25593"
      - "25594:25594"
      - "25595:25595"
      - "25596:25596"
      - "25597:25597"
      - "25598:25598"
      - "25599:25599"
      - "25600:25600"
    environment:
      - APP_NAME=BlockPanel
      - APP_VERSION=${BLOCKPANEL_TAG:-v0.3.2}
      - USE_POSTGRES=false
      - DATABASE_URL=sqlite:///./minecraft_controller.db
      - SERVERS_CONTAINER_ROOT=/data/servers
      - SERVERS_VOLUME_NAME=minecraft-controller_mc_servers_data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY:-change-me-single-container-secret}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - mc_servers_data:/data/servers
      - /var/run/docker.sock:/var/run/docker.sock
      # Persist SQLite file by binding the work directory db file out if desired:
      - sqlite_data:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/quick"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Lightweight one-shot container that pre-pulls the runtime image used for
  # building/running different Minecraft server types & versions (Fabric/Forge/etc.).
  # This speeds up the first server creation because the image layer fetch happens now.
  runtime_prewarm:
    image: ${BLOCKPANEL_RUNTIME_IMAGE:-moresonsun/blockypanel-runtime}:${BLOCKPANEL_TAG:-latest}
    container_name: blockpanel-runtime-prewarm
    command: ["true"]
    restart: "no"
    # If you don't want this behavior, you can comment this service out safely.

volumes:
  mc_servers_data:
  sqlite_data:
