STEAM_GAMES = {
    "palworld": {
        "display_name": "Palworld",
        "summary": "Co-op creature survival shooter with heavy CPU load on busy worlds.",
        "notes": "Set a strong admin password and monitor CPU usage as bases grow.",
        "default_name": "palworld",
        "image": "thijsvanloef/palworld-server-docker:latest",
        "ports": [
            {"container": 8211, "protocol": "udp"},
            {"container": 27015, "protocol": "udp"},
        ],
        "env": {
            "PUID": 1000,
            "PGID": 1000,
            "TZ": "UTC",
            "SERVER_NAME": "Palworld Server",
            "SERVER_PASSWORD": "change-me",
            "ADMIN_PASSWORD": "admin",
        },
        "volume": {"container": "/palworld"},
    },
    "project_zomboid": {
        "display_name": "Project Zomboid",
        "summary": "Isometric zombie survival with persistent worlds and RCON support.",
        "notes": "Watch RAM usage for large maps and set an admin password.",
        "default_name": "zomboid",
        "image": "pyrated/project-zomboid:latest",
        "ports": [
            {"container": 16261, "protocol": "udp"},
            {"container": 16262, "protocol": "tcp"},
        ],
        "env": {
            "PUID": 1000,
            "PGID": 1000,
            "TZ": "UTC",
            "ADMIN_PASSWORD": "admin",
            "SERVER_NAME": "Zomboid Server",
        },
        "volume": {"container": "/home/steam/Zomboid"},
    },
    "valheim": {
        "display_name": "Valheim",
        "summary": "Popular Viking survival sandbox supporting up to 10 players.",
        "notes": "Configure world name and server password; open UDP ports 2456-2458.",
        "default_name": "valheim",
        "image": "lloesche/valheim-server:latest",
        "ports": [
            {"container": 2456, "protocol": "udp"},
            {"container": 2457, "protocol": "udp"},
            {"container": 2458, "protocol": "udp"},
        ],
        "env": {
            "SERVER_NAME": "Valheim Server",
            "WORLD_NAME": "Dedicated",
            "SERVER_PASS": "change-me",
        },
        "volume": {"container": "/config"},
    },
    "tmodloader": {
        "display_name": "Terraria (tModLoader)",
        "summary": "Modded Terraria server via tModLoader with SteamCMD builds.",
        "notes": "Set world seed, max players, and password as desired.",
        "default_name": "tmodloader",
        "image": "ghcr.io/beardedio/terraria:latest",
        "ports": [
            {"container": 7777, "protocol": "tcp"},
        ],
        "env": {
            "WORLD_NAME": "Dedicated",
            "MAX_PLAYERS": 8,
            "TYPE": "tmodloader",
            "WORLD_FILENAME": "Dedicated.wld",
            "WORLD_SIZE": 3,
            "WORLD_DIFFICULTY": 1,
            "WORLD_SEED": "",
        },
        "volume": {"container": "/config"},
    },
    "cs2": {
        "display_name": "Counter-Strike 2",
        "summary": "Dedicated CS2 server with tickrate and RCON configuration.",
        "notes": "Open both UDP and TCP 27015. Configure RCON and lobby passwords.",
        "default_name": "cs2",
        "image": "cm2network/cs2:latest",
        "ports": [
            {"container": 27015, "protocol": "udp"},
            {"container": 27015, "protocol": "tcp"},
        ],
        "env": {
            "SRCDS_RCONPW": "change-me",
            "SRCDS_PW": "",
            "SRCDS_TV_PW": "",
            "SRCDS_FPSMAX": 300,
            "SRCDS_TICKRATE": 128,
        },
        "volume": {"container": "/home/steam/cs2-dedicated"},
    },
    "factorio": {
        "display_name": "Factorio",
        "summary": "Automation factory builder with deterministic saves and mods.",
        "notes": "Enable save/backups and set a server password if needed.",
        "default_name": "factorio",
        "image": "factoriotools/factorio:stable",
        "ports": [
            {"container": 34197, "protocol": "udp"},
        ],
        "env": {
            "SERVER_NAME": "Factorio Server",
            "SERVER_PASSWORD": "",
            "LOAD_LATEST_SAVE": "true",
        },
        "volume": {"container": "/factorio"},
    },
}
